name: mrcavirtuals
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  provider: ^6.1.5
  firebase_auth: ^5.5.3
  flutter_spinkit: ^5.2.1
  youtube_player_flutter: ^9.1.1
  shared_preferences: ^2.5.3
  google_sign_in: ^6.3.0
  url_launcher: ^6.3.1
  wakelock_plus: ^1.3.2
  secure_content: ^1.0.1
  flutter_portal: ^1.1.4
  encrypt: ^5.0.3
  flutter_root_checker: ^1.0.1
  device_info_plus: ^11.4.0
  intl: ^0.20.2
  flutter_pdfview: ^1.4.0+1
  http: ^1.4.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

