// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUI9AjSZ8Qu1KI8RYuKhUmfmKuhG-4Xw4',
    appId: '1:699455540180:web:183f3e06eaef7f681d6441',
    messagingSenderId: '699455540180',
    projectId: 'mr-ca-virtuals',
    authDomain: 'mr-ca-virtuals.firebaseapp.com',
    storageBucket: 'mr-ca-virtuals.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzZZsCgU0hTXQUGBjBtswjigB4uUnIAB0',
    appId: '1:699455540180:android:a6cb466ca56063781d6441',
    messagingSenderId: '699455540180',
    projectId: 'mr-ca-virtuals',
    storageBucket: 'mr-ca-virtuals.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_PDX3XIqwbs2CUEkBXq-oq9qwmbrmgCc',
    appId: '1:699455540180:ios:4f913e726e6e9b231d6441',
    messagingSenderId: '699455540180',
    projectId: 'mr-ca-virtuals',
    storageBucket: 'mr-ca-virtuals.firebasestorage.app',
    androidClientId: '699455540180-052bfg5l7qq9immjmbgarotr6g4bf196.apps.googleusercontent.com',
    iosClientId: '699455540180-52rcfpuu7g6bo95g50mdsqeig71i2j93.apps.googleusercontent.com',
    iosBundleId: 'com.kirubakaran.mrcavirtuals',
  );
}
